version: "3.8"
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3,lambda,dynamodb,cloudwatch, iam
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker-reuse
    ports:
      - "4566:4566" 
      - "4571:4571" 
